stages:
    - publish

before_script:
    - "cd tricit"

publish:
    stage: publish
    script:
         - "dotnet publish -f netcoreapp2.2 -c Release -r linux-x64"
         - "cd tricit/bin/Release/netcoreapp2.2/linux-x64/publish/"
         - "zip -r ~/deploys/traceItBO_linux.zip *"
